# Generated by Django 5.1.1 on 2024-11-10 00:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=100)),
                ('required_skills', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('match_percentage', models.FloatField(null=True)),
                ('resume_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('matched_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_app.jobprofile')),
            ],
        ),
    ]
