# Generated by Django 5.1.1 on 2024-11-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='profile_name',
            field=models.CharField(max_length=225),
        ),
    ]
