# Generated by Django 5.1.1 on 2024-11-10 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_alter_jobprofile_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobprofile',
            old_name='profile_name',
            new_name='job_title',
        ),
    ]
