# Generated by Django 5.1.1 on 2024-11-30 19:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_rename_profile_name_jobprofile_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='match_percentage',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='matched_profile',
        ),
        migrations.AddField(
            model_name='resume',
            name='backend_developer_non_python',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='backend_developer_python',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='dba',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='devops',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='python_data_analyst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='ui_developer_angular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='ui_developer_react',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='ux_designer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
