# Generated by Django 5.1.1 on 2024-11-30 19:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0004_remove_resume_match_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='backend_developer_non_python',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='backend_developer_python',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='dba',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='devops',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='python_data_analyst',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='ui_developer_angular',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='ui_developer_react',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='ux_designer',
        ),
        migrations.AddField(
            model_name='resume',
            name='match_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='matched_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_app.jobprofile'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
