# Generated by Django 5.1.1 on 2024-11-30 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0005_remove_resume_backend_developer_non_python_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='resumes',
            field=models.ManyToManyField(blank=True, related_name='job_profiles', to='resume_app.resume'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='matched_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume_app.jobprofile'),
        ),
    ]
