# Generated by Django 5.1.1 on 2024-11-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0006_jobprofile_resumes_alter_resume_matched_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprofile',
            name='resumes',
        ),
        migrations.AlterField(
            model_name='resume',
            name='matched_profile',
            field=models.CharField(default='No match', max_length=255),
        ),
    ]
